name: Build Blog Every 10 Days

on:
  schedule:
    - cron: '0 0 */10 * *' # Every 10 days at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build blog
        run: npm run build

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add blog/index.html
          git commit -m 'chore: auto-build blog [skip ci]' || echo "No changes to commit"
          git push 